steps:
  # The following step starts the build process using Gradle official image, performs the build
  # and runs `jib` for the specified `gcpProject` in order to build and deploy the container
  # image to the Google Container Registry.
  - name: 'gradle:6.4.1-jdk11'
    entrypoint: 'gradle'
    args: [ 'build', 'jib', '-PgcpProject=${PROJECT_ID}' ]
  # The following step deploys the previously produced container image to the Cloud Run environment
  # with the pre-configured `GCP_PROJECT_ID` environment variable.
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}',
      '--set-env-vars', 'GCP_PROJECT_ID=${PROJECT_ID}',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--project', '${PROJECT_ID}'
    ]
timeout: 1200s
substitutions:
  _SERVICE_NAME: "chat-bot-server"
