#
# Copyright 2021, TeamDev. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Redistribution and use in source and/or binary forms, with or without
# modification, must retain the above copyright notice and the following
# disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

steps:
  # The following step starts the build process using Gradle official image, performs the build
  # and runs `jib` for the specified `GCP_PROJECT` in order to build and deploy the container
  # image to the Google Container Registry.
  - name: 'gradle:7.3-jdk17'
    entrypoint: 'gradle'
    args: [ 'build', 'jib', '-PGCP_PROJECT=${PROJECT_ID}' ]
    env: ["GITHUB_ACTOR=CloudBuild"]
    secretEnv: ["GITHUB_TOKEN"]
  # The following step deploys the previously produced container image to the Cloud Run environment
  # with the pre-configured `GCP_PROJECT_ID` environment variable.
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}',
      '--set-env-vars', 'GCP_PROJECT_ID=${PROJECT_ID}',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--project', '${PROJECT_ID}'
    ]
timeout: 1200s
substitutions:
  _SERVICE_NAME: "chat-bot-server"
availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/GithubToken/versions/latest"
      env: "GITHUB_TOKEN"
