steps:
  - name: 'gradle:6.4.1-jdk11'
    entrypoint: 'gradle'
    args: [ 'build', 'jib', '-PgcpProject=${PROJECT_ID}' ]
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--project', '${PROJECT_ID}'
    ]
timeout: 1200s
substitutions:
  _SERVICE_NAME: "chat-bot-server"

images: [
  'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
]
