### List Travis CI builds for a repository

GET https://{{host}}/repo/SpineEventEngine%2Fcore-java/builds?limit=3&branch.name=master&include=build.commit
Accept: application/json
Authorization: token {{token}}
Travis-API-Version: 3

### List Travis CI repositories for a user

GET https://{{host}}/owner/SpineEventEngine/repos
Accept: application/json
Authorization: token {{token}}
Travis-API-Version: 3

### List Travis CI repository branch builds

GET https://{{host}}/repo/SpineEventEngine%2Fcore-java/branch/master?include=build.commit,build.created_by
Accept: application/json
Authorization: token {{token}}
Travis-API-Version: 3
